# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: keras_grpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'keras_grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10keras_grpc.proto\x12\x05keras\"/\n\x0cImageRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"S\n\x12PredictionResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x17\n\x0fpredicted_class\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x32L\n\x0fKerasPrediction\x12\x39\n\x07Predict\x12\x13.keras.ImageRequest\x1a\x19.keras.PredictionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keras_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=27
  _globals['_IMAGEREQUEST']._serialized_end=74
  _globals['_PREDICTIONRESPONSE']._serialized_start=76
  _globals['_PREDICTIONRESPONSE']._serialized_end=159
  _globals['_KERASPREDICTION']._serialized_start=161
  _globals['_KERASPREDICTION']._serialized_end=237
# @@protoc_insertion_point(module_scope)
